CREATE TABLE "GCG_6873_REC_CHANGE"(
 "REC_NO" IDENTITY,
 "USER_ID" CHAR(8),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "DATE_CHANGE" DATETIME,
 "DATE_RECORD" DATE,
 "REASON" CHAR(50),
 "NOTE" LONGVARCHAR,
 "PREVIOUS_HRS" DOUBLE,
 "NEW_HRS" DOUBLE,
 "CHG_BY" CHAR(8) );

CREATE INDEX "GCG_6873_REC_CHANGE" ON "GCG_6873_REC_CHANGE"("REC_NO", "USER_ID", "JOB", "SUFFIX", "SEQ");